global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cockroachdb'
    static_configs:
      - targets: ['cockroachdb:6565']
    metrics_path: '/_status/vars'
    scheme: 'http'
    scrape_interval: 30s
